[package]
name = "schule"
version = "1.0.1"
entrypoint = "src/schule.typ"
authors = ["J. Neugebauer <https://github.com/jneug>"]
license = "MIT"
description = "Vorlagen und Makros f√ºr die Schule."
homepage = "https://github.com/jneug/schule-typst"
repository = "https://github.com/jneug/schule-typst"
disciplines = [
    "computer-science",
    "education",
    "mathematics",
]
exclude = [
    ".github",
    "docs",
    "scripts",
    "tests",
    ".typstignore",
    "Justfile",
]

