[package]
name = "schule"
version = "0.0.5"
entrypoint = "schule.typ"
authors = ["J. Neugebauer"]
license = "MIT"
description = "Arbeitsbl√§tter und Klausuren."
repository = "https://github.com/jneug/schule-typst"
